#+TITLE: Notes on the book "On Death and Dying" by Dr. Elisabeth Kübler-Ross
#+DATE: <2015-03-23 Mon>
#+FILETAGS: :book-review:

#+begin_export html
<div class="clipping">
<span class="content">
<p class="highlight">Death belongs to life as birth does. The walk is in the raising of the foot as in the laying of it down.</p>
</span>
<span class="information">
<span class="page">Page:
<ul><li>269</li></ul>
</span>
<span class="location">Location:
<ul><li>4647</li><li>4649</li></ul>
</span>
</span>
</div>
#+end_export

[[http://www.amazon.com/gp/product/0684842238/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0684842238&linkCode=as2&tag=joelfran-20&linkId=TL5H4GUXRI6XLEAH][On Death and Dying]]
is a book that "brought about a radical restructuring of patients' relationships with their doctors and other clinicians". If you've heard about the "[[https://en.wikipedia.org/wiki/K%C3%BCbler-Ross_model#Stages][five stages of grief]]", this book is where that model came from.

Indeed, this book was so influential that, according to the introduction to my version of the book:

#+begin_export html
<div class="clipping">
<span class="content">
<p class="highlight">by the late 1990s pain would become a "fifth vital sign" to be assessed in hospitals every time a patient's temperature, pulse, blood pressure, and respirations were measured.</p>
</span>
<span class="information">
<span class="location">Location:
<ul><li>82</li><li>84</li></ul>
</span>
</span>
</div>
#+end_export

The best parts of this book are the many transcribed interviews that it contains. My highlights consist mostly of the comments or summaries that Kübler-Ross had on these interviews. However, the interviews themselves are what make the book.

My highlights on this book fall into a few categories:

1. Insights into the modern views of death
2. The importance of facing our own mortality
3. How to interact with the dying
4. Closing thoughts from the author

* Insights into the modern views of death

#+begin_export html
<div class="clipping">
<span class="content">
<p class="highlight">The more we are making advancements in science, the more we seem to fear and deny the reality of death. How is this possible?</p>
</span>
<span class="information">
<span class="location">Location:
<ul>
<li>243</li>
<li>244</li>
</ul>
</span>
</span>
</div>

<div class="clipping">
<span class="content">
<p class="highlight">I think there are many reasons for this flight away from facing death calmly. One of the most important facts is that dying nowadays is more gruesome in many ways, namely, more lonely, mechanical, and dehumanized;</p>
</span>
<span class="information">
<span class="location">Location:
<ul>
<li>249</li>
<li>250</li>
</ul>
</span>
</span>
</div>
#+end_export

Another insight from the book, that I wasn't able to capture in a highlight, is that advances in science have made dying harder. It's more rare for someone to accept death in our modern age, because a "cure" could legitimacy be around the corner.

#+begin_export html
<div class="clipping">
<span class="content">
<p class="highlight">In simple terms, in our unconscious mind we can only be killed; it is inconceivable to die of a natural cause or of old age. Therefore death in itself is associated with a bad act, a frightening happening, something that in itself calls for retribution and punishment.</p>
</span>
<span class="information">
<span class="location">Location:
<ul>
<li>171</li>
<li>172</li>
</ul>
</span>
</span>
</div>

<div class="clipping">
<span class="content">
<p class="highlight">man has not basically changed. Death is still a fearful, frightening happening, and the fear of death is a universal fear even if we think we have mastered it on many levels. What has changed is our way of coping and dealing with death and dying and our dying patients.</p>
</span>
<span class="information">
<span class="location">Location:
<ul>
<li>208</li>
<li>210</li>
</ul>
</span>
</span>
</div>
#+end_export

* The importance of facing our own mortality

#+begin_export html
<div class="clipping">
<span class="content">
<p class="highlight">Each one of us has the need to avoid this issue, yet each one of us has to face it sooner or later. If all of us could make a start by contemplating the possibility of our own personal death, we may effect many things, most important of all the welfare of our patients, our families, and finally perhaps our nation.</p>
</span>
<span class="information">
<span class="page">Page:
<ul>
<li>31</li>
</ul>
</span>
<span class="location">Location:
<ul>
<li>380</li>
<li>382</li>
</ul>
</span>
</span>
</div>


<div class="clipping">
	<span class="content">
	<p class="highlight">It may be a blessing, therefore, to use the time of illness to think about death and dying in terms of ourselves, regardless of whether the patient will have to meet death or get an extension of life.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>42</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>556</li>
              <li>558</li>
            </ul>
          </span>
        </span>
     </div>

<div class="clipping">
	<span class="content">
	<p class="highlight">If we are willing to take an honest look at ourselves, it can help us in our own growth and maturity. No work is better suited for this than the dealing with very sick, old, or dying patients.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>62</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>845</li>
              <li>846</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">After the occurrence of cancer he spared every moment to be with them, but by then, it seemed to be too late. His daughter was away at school and had her own friends. When she was small and needed and wanted him, he was too busy making money.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>181</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>2975</li>
              <li>2977</li>
            </ul>
          </span>
        </span>
</div>
#+end_export

* How to interact with the dying

#+begin_export html
<div class="clipping">
	<span class="content">
	<p class="highlight">let the relative talk, cry, or scream if necessary. Let them share and ventilate, but be available. The relative has a long time of mourning ahead of him, when the problems for the dead are solved.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>186</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>3044</li>
              <li>3046</li>
            </ul>
          </span>
        </span>
      </div>

<div class="clipping">
	<span class="content">
	<p class="highlight">STUDENT: Do you feel very depressed when you're alone? PATIENT: Yes, I kind of panic because I like people and I like to be around people and being with someone . . . I don't know, when I'm alone all the problems come up. Sometimes you do feel more depressed when there's nobody there to talk to.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>208</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>3533</li>
              <li>3536</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">The majority of patients welcomed a breakthrough of their defenses, were relieved when they did not have to play a game of superficial conversation when deep down they were so troubled with real or unrealistic fears.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>259</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>4502</li>
              <li>4504</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">The patients respond often with almost exaggerated appreciation to someone who cares and who takes a little time out. They are deprived of such kindnesses in a busy world of gadgets and numbers and it is not surprising, then, that a little touch of humanity elicits such an overwhelming response.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>262</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>4550</li>
              <li>4552</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">The fact that children are allowed to stay at home where a fatality has stricken and are included in the talk, discussions, and fears gives them the feeling that they are not alone in the grief and gives them the comfort of shared responsibility and shared mourning. It prepares them gradually and helps them view death as part of life, an experience which may help them grow and mature.</p>
	</span>
        <span class="information">
          <span class="location">Location:
            <ul>
              <li>229</li>
              <li>232</li>
            </ul>
          </span>
        </span>
      </div>
#+end_export

I feel like this is true in the general case too:

#+begin_export html
<div class="clipping">
	<span class="content">
	<p class="highlight">The tragedy is perhaps that we do not think of the reasons for patients' anger and take it personally, when it has originally nothing or little to do with the people who become the target of the anger.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>65</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>886</li>
              <li>887</li>
            </ul>
          </span>
        </span>
</div>



<div class="clipping">
	<span class="content">
	<p class="highlight">CHAPLAIN: It destroys the meaning of it. PATIENT: It isn't right. I can't beg somebody for something that I need.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>89</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>1332</li>
              <li>1333</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">Our initial reaction to sad people is usually to try to cheer them up, to tell them not to look at things so grimly or so hopelessly. We encourage them to look at the bright side of life, at all the colorful, positive things around them. This is often an expression of our own needs, our own inability to tolerate a long face over any extended period of time.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>99</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>1452</li>
              <li>1454</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">this type of depression is necessary and beneficial if the patient is to die in a stage of acceptance and peace. Only patients who have been able to work through their anguish and anxieties are able to achieve this stage.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>100</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>1476</li>
              <li>1478</li>
            </ul>
          </span>
        </span>
</div>
#+end_export

The people taking care of the dying also need to take time to themselves:

#+begin_export html
<div class="clipping">
	<span class="content">
	<p class="highlight">I think it is cruel to expect the constant presence of any one family member. Just as we have to breathe in and breathe out, people have to "recharge their batteries" outside the sickroom at times, live a normal life from time to time;</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>167</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>2738</li>
              <li>2740</li>
            </ul>
          </span>
        </span>
</div>


<div class="clipping">
	<span class="content">
	<p class="highlight">Just as the terminally ill patient cannot face death all the time, the family member cannot and should not exclude all other interactions for the sake of being with the patient exclusively.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>167</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>2744</li>
              <li>2745</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">When anger, resentment, and guilt can be worked through, the family will then go through a phase of preparatory grief, just as the dying person does. The more this grief can be expressed before death, the less unbearable it becomes afterward.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>176</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>2893</li>
              <li>2895</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">genuine emotions on the part of a member of the family are much easier to take than a make-believe mask which the patient can see through anyway and which means to him a disguise rather than a sharing of a sad situation.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>177</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>2896</li>
              <li>2898</li>
            </ul>
          </span>
        </span>
</div>
#+end_export

* Closing thoughts from the author

#+begin_export html
<div class="clipping">
	<span class="content">
	<p class="highlight">If we attempt to summarize briefly what these patients have taught us, the outstanding fact, to my mind, is that they are all aware of the seriousness of their illness whether they are told or not.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>263</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>4566</li>
              <li>4567</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">They wished to share with an understanding person some of their feelings, especially the ones of anger, rage, envy, guilt, and isolation.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>263</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>4571</li>
              <li>4572</li>
            </ul>
          </span>
        </span>
</div>


<div class="clipping">
	<span class="content">
	<p class="highlight">All of our patients reacted to the bad news in almost identical ways, which is typical not only of the news of fatal illness but seems to be a human reaction to great and unexpected stress: namely, with shock and disbelief.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>265</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>4579</li>
              <li>4580</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">All of our patients reacted to the bad news in almost identical ways, which is typical not only of the news of fatal illness but seems to be a human reaction to great and unexpected stress: namely, with shock and disbelief.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>265</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>4579</li>
              <li>4580</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">When the environment was able to tolerate this anger without taking it personally, the patient was greatly helped in reaching a stage of temporary bargaining followed by depression, which is a stepping-stone towards final acceptance.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>265</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>4584</li>
              <li>4585</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">It appears that people who have gone through a life of suffering, hard work, and labor, who have raised their children and been gratified in their work, have shown greater ease in accepting death with peace and dignity compared to those who have been ambitiously controlling their environment, accumulating material goods, and a great number of social relationships but few meaningful interpersonal relationships which would have been available at the end of life.</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>266</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>4600</li>
              <li>4603</li>
            </ul>
          </span>
        </span>
</div>

<div class="clipping">
	<span class="content">
	<p class="highlight">Was it Montaigne who said that death is just a moment when dying ends?</p>
	</span>
        <span class="information">
          <span class="page">Page:
            <ul>
              <li>268</li>
            </ul>
          </span>
          <span class="location">Location:
            <ul>
              <li>4639</li>
              <li>4640</li>
            </ul>
          </span>
        </span>
</div>
#+end_export

* Comments? Suggestions?

Please [[/contact][contact me]] if you have any comments on this book
or on my notes thereof. Also, I'd love to know about other books, articles,
videos, etc on these topics. Thanks!

--[[/][Joël Franusic]]
