#+TITLE: Fun questions to ask Microsoft employees
#+DATE: <2013-10-02 Wed>

These are questions that I wished people would have asked me when I was a Microsoft employee.

Next time you meet an employee of Microsoft, instead of asking them if they use an iPhone, I suggest that you ask them one or more of the questions below.

Many Microsoft employees won't be able to answer all of these questions, but they should. Some of these questions are designed to give you an opportunity to learn something cool, others are designed to help you educate the Microsoft employee about something they should know.

Ideally, all of these questions are designed to be the start of an interesting conversation.

* Postscript

This post was written in 2012 and published in 2013. In 2014 I wrote this tweet:

#+begin_export html
<blockquote class="twitter-tweet" lang="en"><p>A lot of the changes at Microsoft are changes I would have made myself if I had been given the power of fiat.</p>&mdash; Joël Franusic (@jf) <a href="https://twitter.com/jf/status/540280269098323969">December 3, 2014</a></blockquote>
#+end_export

* Questions

"What was the deal with the Halloween Documents?"

"So, when is the last time you hacked on a project in Visual Studio?"

"Do you have code on GitHub?" (/GitHub/, not CodePlex)

"Why are so many people using Macs these days?" (Don't let them get away with answers like "Because that's what they used in school" or "Because it's trendy to use Macs")

"What's an I/O completion port?"

"Are companies like Google, Facebook, Twitter using Microsoft software in production?"

"Have you read Paul Graham's [[http://www.paulgraham.com/microsoft.html][essays]] [[http://www.paulgraham.com/cliffsnotes.html][on Microsoft]]?"

"What is a y combinator? How would you write one in .NET?"

"What is the Windows equivalent to apt, brew, etc?"

"Why can't I run an unsigned kernel on a Surface?"

"Why doesn't Microsoft make it easier to use the [[http://technet.microsoft.com/library/cc767884.aspx][POSIX subsystem]]"?

"What does Microsoft think of Javascript?"

#+begin_export html
<script src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export
